### ISSUE TITLE
SOS: corrupted file on upload

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [exoscale/cli#137]
bug on exo sos upload
I have tested the download (okay with file uploaded from the web console)

```
$ sha1sum big.video.mkv
87431f013c576b6faa45f105fb7f6946891dcc2c big.video.mkv
```

```
$ exo sos upload buckettest big.video.mkv
done! 100 %  big.video.mkv
```

```

$ exo sos download buckettest  big.video.mkv testdownload.mkv
Successfully downloaded "big.video.mkv" into "testdownload.mkv"
```

```
$ sha1sum testdownload.mkv 
f65c9d28f2715034eee0921eb157643100eab74e testdownload.mkv
```

BUG: checksum are different

Download is okay!

```
$ exo sos download buckettest  big.video.mkv testdownload1.mkv
Successfully downloaded "big.video.mkv" into "testdownload1.mkv"
$ exo sos download buckettest  big.video.mkv testdownload2.mkv
Successfully downloaded "big.video.mkv" into "testdownload2.mkv"
$ exo sos download buckettest  big.video.mkv testdownload3.mkv
Successfully downloaded "big.video.mkv" into "testdownload3.mkv"
```

```
$ sha1sum testdownload*.mkv
f65c9d28f2715034eee0921eb157643100eab74e  testdownload1.mkv
f65c9d28f2715034eee0921eb157643100eab74e  testdownload2.mkv
f65c9d28f2715034eee0921eb157643100eab74e  testdownload3.mkv
```
all download are valid!

**Comment by mcorbin** [comment]
If you download the file manually from SOS, the checksum is ok (the problem is only in the CLI) ?

**Comment by pierre-emmanuelJ** [comment]
the problem is from the exo upload cmd. most of the time on big file

**Comment by bcachet** [comment]
when you upload your file, do you provide md5 information ?
SOS will validate uploaded content with provided md5 and will fail upload if there is a mismatch

**Comment by falzm** [comment]
I've reproduced the issue but didn't find a solution for now. Maybe try to update minio dependency, so switch to Go AWS SDK (never had any issues uploading large files with it, even with SOS): https://godoc.org/github.com/aws/aws-sdk-go/service/s3/s3manager

**Comment by falzm** [comment]
An issue has been opened in the minio-go repository: https://github.com/minio/minio-go/issues/1124
