### ISSUE TITLE
SOS: upload freeze on empty file

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [exoscale/cli#138]
all is in the title

**Comment by falzm** [comment]
Related to https://github.com/vbauerster/mpb/issues/7

**Comment by falzm** [comment]
[Possibly a bug](https://github.com/vbauerster/mpb/issues/7#issuecomment-518756758) in the minio-go package, so I've opened an issue there: https://github.com/minio/minio-go/issues/1146
