### ISSUE TITLE
SOS: add exo sos show cmd

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [exoscale/cli#139]
there is already some cmd to show info like:
exo sos acl list
exo sos header list
exo sos metadata list

but why not add `exo sos show <bucket> <object name>`
to show info like on the web consol (object url) and why not acl, header, meta to have the info quicker

**Comment by falzm** [comment]
Good idea. There is a whole project of portal/CLI alignment to be conducted, but it doesn't hurt to fix some inconsistencies right now ;)

**Comment by illi-j** [comment]
#204
