### ISSUE TITLE
Fix gh-pages website build

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [exoscale/cli#146]
![image](https://user-images.githubusercontent.com/15922119/57622810-b096f600-758e-11e9-88cc-195ae0113974.png)

![image](https://user-images.githubusercontent.com/15922119/57622792-a543ca80-758e-11e9-9958-a2dcae40eb06.png)

**Comment by falzm** [comment]
Fixed 👍

**Comment by pierre-emmanuelJ** [comment]
Thx
