### ISSUE TITLE
config: not written due to endpoint failure

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [exoscale/cli#16]
<a href="https://github.com/marcaurele"><img src="https://avatars3.githubusercontent.com/u/1081566?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marcaurele](https://github.com/marcaurele)**
_Thursday Sep 06, 2018 at 05:41 GMT_
_Originally opened as https://github.com/exoscale/egoscale/issues/318_

----

When the remote endpoint is not available, it's impossible to add an entry and it crashed the whole import.

1. write each configuration entry in the file as soon as possible
2. don't exit when the endpoint does not reply

```
[+] Account name [blabla]: 
Get http://localhost:8080/client/api?apikey=blablablablablabl&command=listZones&page=1&pagesize=50&response=json&signature=blablablablabl%3D: dial tcp [::1]:8080: connect: connection refused
<program exits & no config written>
```

**Comment by falzm** [comment]
Can't reproduce, probably fixed since then.
