### ISSUE TITLE
Managed private networks

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [exoscale/cli#17]
<a href="https://github.com/mcorbin"><img src="https://avatars3.githubusercontent.com/u/4451204?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcorbin](https://github.com/mcorbin)**
_Thursday Sep 13, 2018 at 10:37 GMT_
_Originally opened as https://github.com/exoscale/egoscale/issues/319_

----

Add support for managed private network in Egoscale/Exo cli:

- [x] createNetwork: add the `startip`, `endip`, `netmask` parameters.
- [x] updateNetwork: add the `startip`, `endip`, `netmask` parameters.
- [x] listNetworks: show the `startip`, `endip`, `netmask` parameters in the output.
- [x] addNicToVirtualMachine: add the `ip` parameter.
- [x] updateVmNicIp: this new call should be implemented.

**Comment by mcorbin** [comment]
Everything is merged, I close this issue ;)

**Comment by pierre-emmanuelJ** [comment]
thanks
