### ISSUE TITLE
CLI tries to write into a not connected drive and fails

### ISSUE THREAD

**Issue by denis-exo** [exoscale/cli#271]
The working laptop has a C:\ drive for Windows and another company drive U:\ 
U is only connected if the laptop is on the company network. For some reason, exoscale-cli tries to write into U, even when installed in C. As U is not always connected, the CLI will fail.

Note that the binaries are installed in `C:\exoscale`

**WHEN** U is not connected (not in company network):
```
C:\exoscale>exo config
panic: mkdir U:\: Cannot create a file when that file already exists.

goroutine 1 [running]:
github.com/danielgtaylor/openapi-cli-generator/cli.initConfig(0xf03f91, 0x1, 0x0, 0x0)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/danielgtaylor/openapi-cli-generator/cli/cli.go:154 +0x548
github.com/danielgtaylor/openapi-cli-generator/cli.Init(0xc000097eb0)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/danielgtaylor/openapi-cli-generator/cli/cli.go:58 +0x68
github.com/exoscale/cli/cmd/internal/x.InitCommand(0xf73e74)
        /Users/marc/Documents/Exoscale/git/cli/cmd/internal/x/x.go:18 +0x7a
github.com/exoscale/cli/cmd.init.172()
        /Users/marc/Documents/Exoscale/git/cli/cmd/x.go:16 +0x2d
```

**WHEN** U/the company network is connected, it will create an empty folder **exo** in U:\ 
Connecting will fail, because the company network does not allow access to the API.

So in both cases, the CLI won't work.

<details> 
  <summary>Temporary workaround (switch networks in between)</summary>
   only works for exo config, not neccessary for other commands... <br>
   1. Connect to company network and run `exo config`  <br>
   2. It will fail, because API is not reachable from company network, but it won't crash and ask for the credentials again  <br>
   3. Before retyping the credentials, connect to the non-company network  <br>
   4. It will work now  <br>
</details>

Version: 1.14.0
Windows 10 1809

**Comment by falzm** [comment]
Hi @denis-exo, this issue should be fixed in version 1.19.0 released today – let us know if that's not the case.
