### ISSUE TITLE
Listing runstatus pages does not work

### ISSUE THREAD

**Issue by janoszen** [exoscale/cli#288]
With the latest version of the Exoscale CLI listing runstatus pages does not work:

```
❯ exo runstatus list
error: Runstatus error: Invalid Authorization header
```

Listing virtual machines works. The same issue persists when calling the method directly from the Egoscale library.

**Comment by falzm** [comment]
@janoszen do you use an IAM-based API key in your configuration? If yes, this is a known bug, as the Runstatus API doesn't support them (only native Exoscale organization account API credentials). Sorry for the inconvenience.

**Comment by janoszen** [comment]
Since the other ones are gone now, yes.

**Comment by falzm** [comment]
I'm closing this issue as this issue is not related to the Runstatus implementation in the CLI or in egoscale library. I suggest you reach out to the Exoscale support to be kept in the loop with updates on this topic.

**Comment by janoszen** [comment]
Thanks, not a big deal, I just wanted to implement it for this tool: https://github.com/janoszen/exoscale-account-wiper
