### ISSUE TITLE
Add a `--vanilla` flag to `exo sos list`

### ISSUE THREAD

**Issue by ste-m** [exoscale/cli#29]
Listing objects in buckets is great but gives this kind of output:

     [2018-06-28 12:17:19 UTC] 411 KiB FILENAME_1
     [2018-06-28 12:17:18 UTC] 418 KiB FILENAME_2
     ...

It would be nice to have an option to have the output as filename only, in order to use the list in subsequent commands without having to manipulate the string.

**Comment by pierre-emmanuelJ** [comment]
Thanks for this issue. `--raw`can be great

**Comment by greut** [comment]
or be more like ls.

`ls` vs `ls -l`

**Comment by pierre-emmanuelJ** [comment]
you mean `ls -l` to list like my `--raw` example ?
