### ISSUE TITLE
VM tags from CLI

### ISSUE THREAD

**Issue by Heliosmaster** [exoscale/cli#298]
It looks like it's not possible to set tags to VMs using the CLI. It would be cool to add the option (and filter maybe based on tags?)

**Comment by falzm** [comment]
Hey @Heliosmaster, thank you for the suggestion. We're in the middle of an API transition in the Exoscale tooling, and tags are not fully supported [in the new API](https://openapi-v2.exoscale.com/) yet. I'll go ahead and close this issue for now, as we'll definitely implement tags for all resources as soon as they're supported API-side.
