### ISSUE TITLE
`exo version` does not display version if no config file is present

### ISSUE THREAD

**Issue by retrack** [exoscale/cli#32]
`exo version` does not display version if no config file is present

* current result:
`exo version
Config File "exoscale" Not Found in "[/Users/acr/.exoscale /Users/acr /Users/acr/github/demo/cli]"`

* expected result (even if config not set/correct/present):
`exo version
exo dev n/a (egoscale 0.12.2)`

**Comment by greut** [comment]
thanks @retrack, that's a known bug due to the way cobra/viper handles the configuration. We'll figure out a work around this.
