### ISSUE TITLE
Support client-go credential plugins for authentication to SKS

### ISSUE THREAD

**Issue by mcanevet** [exoscale/cli#322]
Currently to connect to SKS we have to generate a full kubeconfig file with `exo sks kubeconfig ... > kubeconfig.yaml`.
It would be great to be able to have a static kubeconfig file that calls the `exo` binary to retrieve the token dynamically.
Reference: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

**Comment by falzm** [comment]
Hi @mcanevet thank you for the suggestion, it's a good idea – we'll see to have this functionality added 👍

**Comment by falzm** [comment]
@mcanevet support on its way: #323

**Comment by falzm** [comment]
@mcanevet available in version 1.26.0.
