### ISSUE TITLE
API error when provisioning VMs with cloud-init 

### ISSUE THREAD

**Issue by ktomk** [exoscale/cli#358]
**Command**

> ~~~
> exo --quiet vm create vm-github-com-exoscale-cli-issue-boot \
> 			  --cloud-init-file exoscale/cloudinit.yaml \
> 			  --disk 10 \
> 			  --service-offering small \
> 			  --template 'Linux Debian 10 (Buster) 64-bit'
> ~~~

**Error Message**

> error: failure Deploying "vm-github-com-exoscale-cli-issue-boot": API error Unauthorized 401 (ServerAPIException 9999): unable to verify user credentials and/or request signature

**Context**

* exo version:  exo 1.37.0 89b170da (egoscale 0.63.0)
* Zone: de-fra-1
* `exoscale/cloudinit.yaml` Size: 3218 (bytes, as in stat(1))

**Additional Information**

The error does not appear if the file-size is smaller, e.g. a previous Size: 416 (bytes, as in stat(1)).

For me this error blocks use of cloud-init YAML `#cloud-config`, as only adding a couple of lines triggers it.

It _appears_ as if #330 has not covered all of #329 @falzm, @zyegfryed, @xgattuso.

**Comment by ktomk** [comment]
The report didn't contain the files to reproduce, here they are b/a (b FAIL, a OK):

**non-working `exoscale/b/cloudinit.yml`**

~~~
#cloud-config

apt_sources:
  - source: "deb https://packages.sury.org/php $RELEASE main"
    key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQGNBFyPb58BDADTDlJLrGJktWDaUT0tFohjFxy/lL2GcVYp4zB981MWIDC0aIQZ
      ERfUZRaq/ov/LG3F0UhkvouCNrnXiFaKRCeNG52pQM0P/p3gmIOoPO4/jF0o3SK1
      Aapf/NaKTh3EgeYYCnVKuxdXGqyu1JT4qfztsmUGmODzxVr+/YJLP54jrCUgI3lj
      4zEeTBDexQvnlVUF59U1/ipMq4iWqqth8/aMsoZl3Ztfcc87jBFbJIoeQMhZtNZk
      Ik7L15aYIZXWY2byBy6LB42HPm9DwM99l2eY4EXGfAq/UQeYbDGonibBqrDURggH
      rkLfG7ZfoexF67/9S2s6VYfS4npWVfw2SEPTfSBdibElbGncd+p9Wb6SovqapCPl
      crkLgPhBAz/R9M7E/G3zedmiEhsV78pBF3bup+nQVvBVtV/NucN5N6LkAclT4O3F
      flGZa1/mJcpgjVapT6duY0POXczfS6ts55x2BE0UfYtXfRnVnHtu2+j8kqYG3N1G
      sfVnzRkwtTWBMxMAEQEAAbQxREVCLlNVUlkuT1JHIEF1dG9tYXRpYyBTaWduaW5n
      IEtleSA8ZGViQHN1cnkub3JnPokB1AQTAQoAPgIbAwULCQgHAgYVCgkICwIEFgID
      AQIeAQIXgBYhBBUFhQCgI12X9dEAY7GI4raVvUdDBQJgK4WHBQkJP7BoAAoJELGI
      4raVvUdDQ/QL+wa0KQ8o8askks4elU1PSdUP/ywacroMtl6BV2d/di/PtquZl4zI
      p/qAhUmcSJhUJMJBdGQ5S4uxCn0rEy2CBO8LhSTFuS01UGVHhjZQLA+GZEMunpS8
      KbPH5lWuwWwY1bbx9eCwpIxzz3Krctk8WGvja4EsqIWmRcaQ1z19JndbH8Ekfhf2
      U7noZNFZIhHIOHK51dOm4oaSdrJUhhd52zrwLf+lOtHh0kkOad+eCByah9XwmO9q
      SAuHLquSv9BWfnLKSHfwRW+YeAHlkELui0Zi6zD2PYqcBAebZWNmyxiJUz0oHJPJ
      H6DoXXxI6OsCdFDkqW5hP/IfVI97fbKMGY9g4RyasJmb/18F7eSFC1S7fj6hHCRn
      HTKR5cO3PdzYndyICGfaQMUa+n0HsWZAw8mgWPnKZd3xXt4n+Exx/LBV3ZkOwHT7
      L9nTPALsoqqEtn0zjOo/eOt9fmaW9TcvL1V1oiRpEk3lejvF/Wt5zwkPOgys2ZCZ
      Ttefx/lGoxC2lrkBjQRcj2+fAQwA4McaM/y2XQSHlJBSYR7yqZtHX/kZ8g9pnViq
      kCEADz8XKCroEzvY1gaWtR6obtjaq8pF0g4KtAC65/gIOtsHvWg3OclrODPkXN+x
      OM1LpXZGV6kwk+LXOrybtPhVZe3FtvDMW0MVZeHYi+soZ4tTQHkKjZUPAXZs3ZoZ
      rWfE5ft447sCxzX+jxDwwlckkKqZ9sHYD0TV8Y5av3RsxiWBt+coch8jvw+1mDZ0
      zBjMO8ZRD8PuvP9UTKCNOIm0mW9A2cUfpkk/uAwo5hCnw4iljS81/KKGM/scwc5K
      x6G3WWoAb8kajt0VFG/wYN2qjfjdhXtdu3ZxYtDdjA2UGGRbgkCsr+gRCnSTiuwv
      LzCVZCz9WNzZjUMg6LFP2IrHned4Kdy4KjJo+g/weKJoxfKokZ/9vUYpw5OYx3UE
      SUk3yHDN9r/JC4RJJ2tE2qkeggJ892RJGxUK/Lw3/7jIQKalO3Qx2zYUqnCYMC9g
      PhQGH+F9kwSpGVwb0DKFT6gR9Pt3ABEBAAGJAbwEGAEKACYCGwwWIQQVBYUAoCNd
      l/XRAGOxiOK2lb1HQwUCYCuFsQUJCT+wkgAKCRCxiOK2lb1HQ3icDADGRBYuqFNG
      2mnAKH9W2qMKGJUBOMdEouUpFZELs5bgMfLH9/i5PNi+73IhHqsSsR3JIHRPuzt5
      nmifWYFPvsVV/8eu2O1UeyCbt+KK1v+aMfJbg3J38pCLgqOrMK1a3VxKZ6mHIy6A
      5xEBLdl9HP6+lGYhYPdQd2kq5H+64DyF5zlpUX9biTpiri4ZiF3kUrXKLEupUtuS
      aWf+n4hTreT2olThoQIsxWPj+YV/9irNRpATY+JrD74tA3HPI02nq3Xvaz0R0gVG
      8HRUcw3ejXgn8SfSmY8p3JxVtYQJTUdsR3+qTgm+91LpFhWBBJZagjUoYrGb5/ZU
      iCyr1kJMo+/PceVsGuiaH9r84fxi0VGZVl4P9rP3Dwx8QLosFrElkQBhX1YIYhJX
      mo/XAlzVedQ37DyJu+/TZDUXu1q/4D+7z0s3oekWmUwziFI1HBxsNbwHRQyek/To
      nirX97CSifEBg1L8BRRex7eUGWJ/YI/Zjf6CNaqUt5SIUBUv0zv1lFc=
      =gNGr
      -----END PGP PUBLIC KEY BLOCK-----

package_upgrade: true
packages:
  - curl
  - [screen, htop]
  - [php7.4-fpm]

runcmd:
  - |
    printenv | sort
    curl http://169.254.169.254/latest/user-data
    curl http://169.254.169.254/latest/meta-data
    printf '%s\n' "$(curl http://169.254.169.254/latest/meta-data/public-ipv4)"
~~~

**working `exoscale/a/cloudinit.yml`**

~~~
#cloud-config

package_upgrade: true
packages:
  - curl
  - [screen, htop]
  - [php7.4-fpm]

runcmd:
  - |
    printenv | sort
    curl http://169.254.169.254/latest/user-data
    curl http://169.254.169.254/latest/meta-data
    printf '%s\n' "$(curl http://169.254.169.254/latest/meta-data/public-ipv4)"
~~~

**Comment by zyegfryed** [comment]
Hi @ktomk,

I am able to reproduce your issue. We will provide a fix ASAP, most probably next week.

In the meantime, I noticed some unrelated issues with your `cloud-init` configuration:

1. invalid apt sources definition, according to [Additional apt configuration and repositories](https://cloudinit.readthedocs.io/en/20.2/topics/examples.html#additional-apt-configuration-and-repositories),
2. invalid package definition, according to [Install arbitrary packages](https://cloudinit.readthedocs.io/en/20.2/topics/examples.html#install-arbitrary-packages).

Here's a [corrected cloud-config file][1] based on `exoscale/b/cloudinit.yml`. Check the [last revision](https://gist.github.com/zyegfryed/5cfb04dd0c6ba61515cd664078e998a5/revisions) to see the fixes.


[1]: https://gist.github.com/zyegfryed/5cfb04dd0c6ba61515cd664078e998a5

**Comment by ktomk** [comment]
> I am able to reproduce your issue. We will provide a fix ASAP, most probably next week.

I guess this falls still into the 99.95%.

> In the meantime, I noticed some unrelated issues with your cloud-init configuration: ...

Great you spotted these, it's from testing against various, so you find 0.7.7 artifacts as well as non-existing packages. It demonstrates these are not the cause of the issue @zyegfryed

(a more clean reproduce example would be a single file with just a comment in it of such a size that triggers around +/- the single byte - if possible)

**Comment by ktomk** [comment]
Just seeing a _similar_ error picture with a different command and _not_ size related but triggered by a character `~`:

~~~
	exo vm template register template-exoscale \
		--description 'desc://io.example.exoscale.vm/~usr/test' \
               ...
~~~

> Exporting snapshot "e9d4c ... 10ce". success
Registering the template. failure
error: API error Unauthorized 401 (ServerAPIException 9999): unable to verify user credentials and/or request signature

leaving the tilde (`~`) out prevents the error.

(just in case there is some relation, e.g. a bug cluser. I'm fine w/ deferring it and create a new report for it later as it is easy to work-around for me)

**Comment by falzm** [comment]
@ktomk can you please try with `exo compute instance create` instead of `exo vm create`? The latter is known to be subject to signature errors with some user data configurations, and `exo vm *` commands will be replaced with `exo compute instance` commands in the near future.

**Comment by ktomk** [comment]
> can you please try with `exo compute instance create` instead of `exo vm create`?

yes, I'd like to do that, and it seems to not be error-prone on the cloud-init userdata, however it seems that not temporary ssh key is generated like `exo vm create` did. @falzm

**Comment by falzm** [comment]
@ktomk indeed, the new Exoscale API that this command uses doesn't allow creating SSH keys anymore, only registering existing ones.

**Comment by ktomk** [comment]
Wondering if it's possible to create single-use (temporary) SSH keys with `exo` then @falzm.

**Comment by falzm** [comment]
@ktomk we could indeed create a single-use key from the CLI directly and register it on the user's behalf before creating a Compute instance, however can you please create a dedicated GitHub issue for this feature and close this one if the topic is solved?

**Comment by ktomk** [comment]
> however can you please create a dedicated GitHub issue for this feature and close this one if the topic is solved?

Sure, created: https://github.com/exoscale/cli/issues/360 (looks like a feature request towards deprecation of `exo vm create` to me). Would only derail here @falzm.

**Comment by falzm** [comment]
We're still in the process of porting all `exo vm *` commands to `exo compute instance`, so for the time being the `exo vm *` commands are not officially deprecated.

**Comment by ktomk** [comment]
> We're still in the process of porting all exo vm * commands to exo compute instance, so for the time being the exo vm * commands are not officially deprecated.

Okay, then I'm continuing to looking forward for a fix here first @falzm.

**Comment by falzm** [comment]
@ktomk there's a misunderstanding: we won't fix the issue for the `exo vm create` command, the solution is to use `exo compute instance create`. If you need to use an SSH key to log into the Compute instance, please register one beforehand and pass the `--ssh-key` flag.

**Comment by ktomk** [comment]
Certainly not. If you prefer deprecation over the fix, then I'd prefer to close the issue here given I can migrate my scripts to `exo compute instance create` as until I'd have an issue with `exo vm create` - reported here.

And that's just all already, I don't see an issue with that.

If you let me know about the plannings for #306. it should ease closing here and there then as I think I can migrate to `exo compute instance create` with a switch then (for new scripts I can already keep it mind but right now it's - as you noted as well - not a standard deprecation for me even I'm willing to go forward, so please don't read this as ignorance).

**Comment by falzm** [comment]
Understood, we'll prioritize the implementation of #360 to facilitate your transition to the `exo compute instance create` command.

**Comment by falzm** [comment]
@ktomk version 1.39.0 just released now implements a single-use SSH key fallback by default.

**Comment by ktomk** [comment]
> @ktomk version 1.39.0 just released now implements a single-use SSH key fallback by default.

Can confirm `exo compute instance create` replacement for `exo vm create` in exo 1.39.0 69a3e1fd (egoscale 0.66.0) for this issues (my) test-case.

Will do more porting (and complete it) within the next 24h and would follow up then (I don't expect any more errors, the test has showed well complete already).

Thanks a lot for taking care @falzm.

**Comment by ktomk** [comment]
Resolved by migrating form `exo vm ...`  to `exo compute ...`. And this worked for nearly all `exo vm ...` commands for us already.

The only leftover to that regard is `exo vm snapshot create`.

It looks to me that there is no replacement (yet?). It was no problem to port the template command thought (`exo compute instance-template ...`).

This boils down on our end to the following two commands that remain un-ported:

* vm snapshot create
* vm snapshot list

(don't get me wrong, they work, so we keep them)

**Comment by falzm** [comment]
@ktomk version 1.40.0 implements support for Compute instance snapshots with the `exo compute instance snapshot *` commands.

**Comment by ktomk** [comment]
@falzm already started to migrate for these.

something is fishy with `exo compute instance snapshot create`:

* Given `--output-template '{{.ID}}{{"\t"}}{{.Name}}{{"\n"}}'`
* When exo option `--quiet` is in use
* Then there is no output at all.

E.g. 
~~~
exo --quiet compute instance snapshot create --zone <zone> <instance-name> \
    --output-template '{{.ID}}{{"\t"}}{{.Name}}{{"\n"}}'
~~~

I often use this pattern (`exo --quiet` *command* *parameters* *options* `--output-template`) to parse and process results and this is the first time I experience it.

**Comment by falzm** [comment]
@ktomk this is the expected behavior: `--quiet` disables all informative output, this explains why there is not templated output. If you only want to disable non-informative output (e.g. the spinner displayed during the operation processing), simply send *stderr* to `/dev/null`: `exo compute instance snapshot create  --output-template '{{.ID}}{{"\t"}}{{.Name}}{{"\n"}} ... 2>/dev/null`

**Comment by ktomk** [comment]
Let's keep this discussion in an issue of its own: https://github.com/exoscale/cli/issues/364 @falzm
