### ISSUE TITLE
exo compute instance create: create a single-use SSH key

### ISSUE THREAD

**Issue by ktomk** [exoscale/cli#360]
When using `exo vm create` there is the option to have a sing-use SSH key with the new instance created.

With `exo compute instance create` this is not an option.

It would be good to have it as a feature so that when relying it on `exo vm create`  it is easier to have the same experience with migrating to `exo compute instance create`.

**Comment by falzm** [comment]
Feature coming in #361.

**Comment by ktomk** [comment]
> Feature coming in #361.

Thanks for the quick turnaround @falzm, much appreceated.

Can confirm working with exo 1.39.0 69a3e1fd (egoscale 0.66.0).

**Comment by joggie** [comment]
Hi @falzm ,

not sure if I did something wrong, but I don't get an ssh-key when I try this:

`[pleber@pat-devX molecule-exoscale-driver]$ exo version`
`exo 1.44.0 323abc9c (egoscale 0.73.2)`

`[pleber@pat-devX molecule-exoscale-driver]$ exo compute instance create --output-format json --disk-size 10 --template "Linux Ubuntu 20.04 LTS 64-bit" --zone at-vie-1 --instance-type standard.micro --security-group default instance`
 `✔ Creating instance "instance"... 19s`
`{"id":"8a42cf0a-ba18-45ea-983e-3b5351faf991","name":"instance","creation_date":"2021-10-15 10:24:25 +0000 UTC","instance_type":"standard.micro","template_id":"Linux Ubuntu 20.04 LTS 64-bit","zoneid":"at-vie-1","anti_affinity_groups":[],"security_groups":["default"],"private_networks":[],"elastic_ips":[],"ip_address":"185.150.8.177","ipv6_address":"-","ssh_key":"-","disk_size":"10 GiB","state":"running","labels":null}`

Do I have to change something in the command?

**Comment by ktomk** [comment]
you can find the temporary SSH key with the configuration (compare `exo config show`) , the SSH key is not part of the JSON output. Instead the file is named in correlation to the instance-ID. @joggie
