### ISSUE TITLE
--quiet hides output from --output-template in exo compute instance snapshot create

### ISSUE THREAD

**Issue by ktomk** [exoscale/cli#364]
Since 

~~~
$ exo version
exo 1.40.0 bca2cae0 (egoscale 0.66.0)
~~~

the `exo compute instance snapshot create` command output from `--output-template` is hidden when the `exo` option `-Q`, `--quiet` is in use.

Scenario:

Given `--output-template`, when using `--quiet` to hide progress on the standard output channel to only have template output, then no output at all is given.

Commands in use:

// boot a test instance (with minimal cloud-init cloud-config and ssh access)
~~~
exo --quiet firewall create exoscale-cli-sg-github-new-report-boot || :
exo --quiet firewall add exoscale-cli-sg-github-new-report-boot ssh --my-ip || :
exo compute instance create exoscale-cli-vm-github-new-report-boot \
			  --zone de-fra-1 \
			  --cloud-init cloudinit.yaml \
			  --disk-size 10 \
			  --security-group exoscale-cli-sg-github-new-report-boot \
			  --instance-type standard.small \
			  --template 'Linux Debian 10 (Buster) 64-bit'
SSH_HOST="$(exo compute instance show exoscale-cli-vm-github-new-report-boot --output-template '{{.IPAddress}}')"; \
	if test -n "$SSH_HOST"; then ssh-keygen -R "$SSH_HOST"; fi
eval $(exo ssh exoscale-cli-vm-github-new-report-boot -o '-o StrictHostKeyChecking=accept-new -o ConnectTimeout=3 -o ConnectionAttempts=15' --print) head /var/log/cloud-init-output.log
~~~

(the cloud-init cloud-config is actually empty, you can leave it out in this scenario, sorry for the cruft, ssh access technically should not be necessary either, this is testing boilerplate)

// creating a snapshot quietly should output from template (not working on 1.40.0)
~~~
exo --quiet compute instance snapshot create --zone de-fra-1 exoscale-cli-vm-github-new-report-boot \
	--output-template '{{.ID}}{{"\t"}}{{.Name}}{{"\n"}}' \
	| tee snapshot-create-output-quiet | grep '	exoscale-cli-vm-github-new-report-boot_'
~~~

(there is no output at all)

Counter-Test:

~~~
exo compute instance snapshot create --zone de-fra-1 exoscale-cli-vm-github-new-report-boot \
	--output-template '{{.ID}}{{"\t"}}{{.Name}}{{"\n"}}' \
	| tee snapshot-create-output-verbose | grep '	exoscale-cli-vm-github-new-report-boot_'
~~~

(output contains the spinner and the template output at the end)

Counter-Test 2 (/dev/null):

~~~
(exo compute instance snapshot create --zone de-fra-1 exoscale-cli-vm-github-new-report-boot \
	--output-template '{{.ID}}{{"\t"}}{{.Name}}{{"\n"}}' 2>/dev/null) \
	| tee snapshot-create-output-redirect | grep '	exoscale-cli-vm-github-new-report-boot_'
~~~
(output contains the spinner and the template output at the end)

**Comment by ktomk** [comment]
> this is the expected behavior: --quiet disables all informative output ([href](https://github.com/exoscale/cli/issues/358#issuecomment-897404357))

Honestly I did not expect this behaviour; previously - how I used it at least - with 1.40.0 I receive a (public interface) change.

As written the usage-pattern was quite common for me and it seems to be aligned with `--help`:

~~~
$ exo --help | grep -- '--quiet'
  -Q, --quiet                    Quiet mode (disable non-essential command output)
~~~

As the help proposes to me, `--quiet` only affects non-essential command output and I'm using `--output-template` for the output and given an explicit option with argument proposing it would be non-essential appears like a stretch to me.

---

> to disable non-informative output (e.g. the spinner displayed during the operation processing), simply send stderr to /dev/null ([href](https://github.com/exoscale/cli/issues/358#issuecomment-897404357))

This was the first thing I tried yesterday running into the issue as I guessed it might work to remove the spinner output.

And even thought the spinner output is on standard error, the template output (text) is on standard error, too. So I get no output, as any output of interest is on the diagnostic channel, not on the output channel.

---

This _may_ hint why with this sub-command there is an issue with --quiet that comes a bit unexpected - both in your and my understanding.

(this break from `exo vm create snapshot`  to `exo compute instance snapshot create` _might_ be intended on your end, but somehow I sense something is not correct here - with all due respect)

**Comment by falzm** [comment]
> The spinner output is on standard output. Therefore can not be redirected apart from the template output.

You're correct, this is indeed a bug. Thank you for bring this to my attention, I'll fix this right away.

**Comment by falzm** [comment]
Fixed in version 1.40.1.

**Comment by ktomk** [comment]
> You're correct, this is indeed a bug. Thank you for bring this to my attention, I'll fix this right away.

> Fixed in version 1.40.1.

Thanks, already updated and got it working @falzm.

I might have been misguided on the --help output earlier, ran a couple of checks and they confirm to me that the --quiet command usage-pattern I had in my mind didn't apply as stringent as I had in mind. Sorry if this caused confusion, I'm still new with the utility.

**Comment by falzm** [comment]
No worries @ktomk, it's always good to hear feedbacks from our users :)

**Comment by ktomk** [comment]
As you're asking for it: https://github.com/exoscale/cli/issues/366  ;) (very minor)
