### ISSUE TITLE
interactive config does read using Powershell

### ISSUE THREAD

**Issue by greut** [exoscale/cli#37]
The first selection appears, then the question doesn't. 

![askquestion](https://user-images.githubusercontent.com/1388/47771060-194d0e00-dce2-11e8-9579-9b086cadcf0c.png)

Sending y or N goes further though.

**Comment by pierre-emmanuelJ** [comment]
oh thank you! I don't know if this lib ()selector work well with Windows? 
I will check that 👍

**Comment by falzm** [comment]
Can't reproduce, closing for now.
