### ISSUE TITLE
SKS nodepool labels not applied as Kubernetes labels

### ISSUE THREAD

**Issue by rubij** [exoscale/cli#371]
Hello,

It would be pretty nice, when we provision a SKS cluster or add some node pools to one, that the labels given at creation time are also applied on the Kuberntes level (i.e on the nodes) and not only at the Exoscale level. 

For example, running the command : 
exo sks create --description "This is a test SKS Cluster" --label "env=test" --nodepool-name "test" --nodepool-label "nodeenv=test" testsks

...could label (as Node labels) all the future created nodes in the "testsks" cluster with the "env=test" label and the "test" nodepool nodes with the "nodeenv=test" label. 

This is currently not the the case: 
kubectl --kubeconfig test.config get nodes --show-labels
NAME               STATUS   ROLES    AGE     VERSION   LABELS
pool-0f8aa-myftv   Ready    <none>   5m58s   v1.21.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ch-dk-2,kubernetes.io/arch=amd64,kubernetes.io/hostname=pool-0f8aa-myftv,kubernetes.io/os=linux,node.kubernetes.io/instance-type=Medium,topology.kubernetes.io/region=ch-dk-2
pool-0f8aa-xlwci   Ready    <none>   5m54s   v1.21.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ch-dk-2,kubernetes.io/arch=amd64,kubernetes.io/hostname=pool-0f8aa-xlwci,kubernetes.io/os=linux,node.kubernetes.io/instance-type=Medium,topology.kubernetes.io/region=ch-dk-2

Best regards
Jonathan Rubiero

**Comment by falzm** [comment]
Hi @rubij, sorry for the confusion: the `--label` flag actually manages *Exoscale resources* labels, similar to tags that can be used for filtering purposes. Those are not related to the underlying Kubernetes-level resources.

**Comment by falzm** [comment]
@rubij following a recent change API-side, the `--label` SKS Nodepool flag is now also translated into Kubernetes *kubelet* labels.
