### ISSUE TITLE
Typo in the rpm package for exo

### ISSUE THREAD

**Issue by kadomino** [exoscale/cli#372]
There is a typo in the rpm package:
```bash
rpm -ql exoscale-cli 
...
/usr/share/bash-completion/completion/exo
...
```
This should be:
```bash
...
/usr/share/bash-completion/completions/exo
...
```

**Comment by falzm** [comment]
Hi @kadomino, thank you for reporting this bug. It's been fixed in 40fcca3, a new version will be released shortly 👍
