### ISSUE TITLE
Follow Arch packaging guidelines for AUR pkgbuild

### ISSUE THREAD

**Issue by FabioLolix** [exoscale/cli#388]
Follow up to my comment https://aur.archlinux.org/packages/exoscale-cli/#comment-822237

Attached there are 3 pkgbuilds: exoscale-cli (from source), exoscale-cli-bin and exoscale-cli-git ready to go

[exoscale-cli-pkgbuilds.tar.gz](https://github.com/exoscale/cli/files/7192282/exoscale-cli-pkgbuilds.tar.gz)

**Comment by falzm** [comment]
@pyr an opinion on this?

**Comment by sauterp** [comment]
Thank you very much for your contribution @FabioLolix we were able to implement all 3 packages based on it. You are of course acknowledged with a `#Contributor` line in all the PKGBUILD files.
