### ISSUE TITLE
"exo compute ..." -> error: resource not found

### ISSUE THREAD

**Issue by joggie** [exoscale/cli#398]
Hi

I'm currently migrating our toolset from "exo vm" to "exo compute ..." and the new command has problems finding instances.

Example:
```
$ exo version
exo 1.44.0 323abc9c (egoscale 0.73.2)
$ exo compute instance list
┼──────────────────────────────────────┼─────────────────┼──────────┼─────────────────┼─────────────────┼─────────┼
│                  ID                  │      NAME       │   ZONE   │      TYPE       │   IP ADDRESS    │  STATE  │
┼──────────────────────────────────────┼─────────────────┼──────────┼─────────────────┼─────────────────┼─────────┼
│ 8b94a70e-238e-47b8-a355-0a14fc1d1366 │ newAWXtest      │ at-vie-1 │ standard.tiny   │ 194.182.X.X     │ stopped │
┼──────────────────────────────────────┼─────────────────┼──────────┼─────────────────┼─────────────────┼─────────┼
$ exo compute instance show newAWXtest
error: resource not found
$ exo compute instance show 8b94a70e-238e-47b8-a355-0a14fc1d1366
error: resource not found
```

Another Example:
![image](https://user-images.githubusercontent.com/7068939/137711374-36e1cd27-3f5a-4413-a74f-b52a59c5a9cc.png)

It's working for some instances and for others it doesn't... I can edit/see/delete the instance in the webui.

**Comment by falzm** [comment]
@joggie does specifying the zone of the instance using `--zone at-vie-1` works? The CLI commands use your current configuration profile's default zone as default value for the `--zone` flag, so if an instance is in a different zone you'll get this "resource not found" error message.

**Comment by joggie** [comment]
Specifying the zone did work, thanks!
Shouldn't at least the ID be zone independent?

**Comment by falzm** [comment]
@joggie not necessarily (e.g. Exoscale-maintained Compute instance templates have the same ID in every zone).
