### ISSUE TITLE
Support security-group delete with self-rules

### ISSUE THREAD

**Issue by boaks** [exoscale/cli#413]
Deleting a security-group, which contains rules, referring to the group ifself, fails.

```
> exo compute security-group rule add my-group \
    --description "SKS kubelet" \
    --protocol tcp \
    --port 10250 \
    --security-group my-group  
```

```
> exo compute security-group delete my-group -f
 
✔ Deleting Security Group my-group... 0s
error: Delete "https://api-de-fra-1.exoscale.com/v2/security-group/?????": invalid request: conflict
```

For me it seems to be unnecessary complicated, to remove the rules via a script first.
I would appreciate to have a flag similar to " exo compute sks delete ... --nodepools", e.g. "--rules".

**Comment by falzm** [comment]
Hi @boaks, that is indeed a legitimate UX issue: we'll address that soon 👍

**Comment by falzm** [comment]
Next version will feature a new `--delete-rules|-r` flag that can be used to preemptively delete rules before the SG.

**Comment by boaks** [comment]
Thanks a lot! Works great with 1.49.1
