### ISSUE TITLE
Typo in the latest release version number v0.51.3 -> v1.51.3?

### ISSUE THREAD

**Issue by tn-osimis** [exoscale/cli#440]
Hello,

It seems the latest version should've been labeled v1.51.3 instead of [v0.51.3](https://github.com/exoscale/cli/releases/tag/v0.51.3), according to the [changelog](https://github.com/exoscale/cli/blob/v0.51.3/CHANGELOG.md).

**Comment by tn-osimis** [comment]
FYI I'm now seeing v1.51.2 as the latest version, but its [changelog](https://github.com/exoscale/cli/blob/v1.51.2/CHANGELOG.md) still mentions the latest as v1.51.**3**.

I guess it's not a biggie if it's just a mislabeling but might still generate some future confusion.

**Comment by 7fELF** [comment]
Hi @tn-osimis,

Yes, there was a slight issue with the generation of the new tags.
I edited the [release](https://github.com/exoscale/cli/releases/tag/v1.51.2) so it points to the fixed changelog.
