### ISSUE TITLE
Offset flag on dbaas logs has no effect

### ISSUE THREAD

**Issue by cstpdk** [exoscale/cli#443]
Hello,

When using the --offset flag on dbaas logs previously it resulted in a nil error. I guess that is fixed now, probably in #439.  However, the flag seems to be a NOOP now, as illustrated here:
![2022-03-16-103108_543x100_scrot](https://user-images.githubusercontent.com/751851/158560100-2c1fb666-39cb-4329-99b1-08b7806deb1c.png)

Seems it always results in no output when using it

**Comment by 7fELF** [comment]
Hello @cstpdk

The offset flag is not a number but an "Opaque offset identifier".

You can find the identifier in the JSON output of the command:

```
exo dbaas logs toto -l 1 -O json | jq
{
  "first_log_offset": "1654617057485",
  "offset": "1654617057485",
  "logs": [
    {
      "time": "2022-06-07T15:50:57.485613Z",
      "node": "toto-1",
      "unit": "postgresql-14.service",
      "message": "[13-1] pid=852800,user=postgres,db=defaultdb,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=defaultdb application_name=aiven-pruned"
    }
  ]
}

```
