### ISSUE TITLE
'exo compute instance snapshot list' randomly missing snapshots

### ISSUE THREAD

**Issue by joggie** [exoscale/cli#445]
Hi,

"exo compute instance snapshot list" does not work as expected since there are snapshots randomly missing sometimes

![image](https://user-images.githubusercontent.com/7068939/161533357-e215d155-76ca-4b60-b6d5-da2bfc4a9a02.png)

As you can see in the screenshot snapshot "36f58382..." was missing at the first run and present on the second, both commands were executed some seconds apart, and no snapshot was created during this time.

I can run the command multiple times and sometimes a snapshot is randomly missing.

![image](https://user-images.githubusercontent.com/7068939/161534362-f38f2896-033b-46dc-8863-0aa81048299c.png)
Here another example, where one snapshot is missing between 2 runs of the command executed 1 second apart.

It seems that it's always the last snapshot in the list which is missing.
Its hard to reproduce, sometimes it does not happen for a long time.

**Comment by joggie** [comment]
exo 1.51.2 a7e283bb (egoscale 0.86.0)

**Comment by joggie** [comment]
![image](https://user-images.githubusercontent.com/7068939/161535823-29d69ded-c9e9-4ba9-bad7-777d5f7c7fb9.png)

just tried with exo 1.52.1 608fcf5 (egoscale 0.86.0)
same problem

**Comment by joggie** [comment]
I just found out that this also happens with

exo compute instance list

![image](https://user-images.githubusercontent.com/7068939/161934430-358c248a-f345-457e-8253-7aebe7c43fc2.png)

this breaks all my ansible playbooks...

**Comment by kobajagi** [comment]
Bug should be fixed in v1.53.0, @joggie let us know if you can still reproduce it with the new release.

**Comment by kobajagi** [comment]
Closing as solved.
