### ISSUE TITLE
Add CORS support to `exo sos`

### ISSUE THREAD

**Issue by aarongroom** [exoscale/cli#47]
Great job implementing the SOS interface!

It might be useful to consider adding support to update CORS headers with the cli.  The following link provides a helpful overview:

https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

The `s3cmd` tool provides `setcors` and `delcors` commands that provide most of the functionality one might need for typical use cases.

Thanks again!

**Comment by greut** [comment]
As we're relying on the [minio-go] library, it has to be done there first.

[minio-go]: https://github.com/minio/minio-go

**Comment by falzm** [comment]
Implemented in `exo storage cors`.
