### ISSUE TITLE
Old version 1.22.2 in snap

### ISSUE THREAD

**Issue by Ken1Nil** [exoscale/cli#492]
Current version in snap is 1.22.2 from 2020-12-16.

Latest version v1.66.0
Whould be nice if a newer version could be bumped to snap.

### Reproduce:

```
user@ubuntu:~$ snap info exoscale-cli
name:      exoscale-cli
summary:   The Exoscale command line tool
publisher: Exoscale
store-url: https://snapcraft.io/exoscale-cli
license:   Apache-2.0
description: |
  The Exoscale command line tool.

  This snap allows you to use the "exo" command once installed, your
  gateway to the Exoscale platform.

  Getting started:

  `sudo snap install exoscale-cli`

  `exo config`

  `exo vm create my-first-machine`


  Sources:

  Source code for this software is available on github: https://github.com/exoscale/cli
snap-id: XBC1qevH7VWDkhxj3QN0EyR9uCbG5tDE
channels:
  latest/stable:    v1.22.2 2020-12-16 (38) 10MB -
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      v1.22.2 2020-12-16 (38) 10MB -
```

## Question: Why use snap?
Using Github Actions, need exoscale cli to get values. E.g `exo dbaas list -O json | jq .`

### Workaround 1? Errors
Manual installation according to README.md 
```
$ git clone https://github.com/exoscale/cli
$ cd cli
$ git submodule update --init --recursive go.mk
$ make build
```
This errors because github workers that builds from source doesn't put output into `/bin/exo` or `/usr/bin/exo` but in a sub directory `/home/runner/work/_repository_/_repository_/cli/bin/exo`

### Workaround 2? Not future proof
Could simply download .deb file and install it according to https://community.exoscale.com/documentation/tools/exoscale-command-line-interface/#gnulinux

But this limits versions in the future to a specific static cli version.
```
wget https://github.com/exoscale/cli/releases/download/v1.66.0/exoscale-cli_1.66.0_linux_amd64.deb
sudo dpkg -i exoscale-cli_1.66.0_linux_amd64.deb
``` 

### Solution
Bump versions to snap

or

Change `make build` to actually export the output to `/bin/exo ` when running it on Github Actions workers?

**Comment by sauterp** [comment]
Thanks for reaching out.

In Workaround 1 you can run `go build -o /home/runner/work/_repository_/_repository_/cli/bin/exo` instead of `make build`.

It sounds to me like, what you are looking for is a way to install the latest version of exoscale cli with a command/script that never changes. I think it would make sense for us to provide this option. Snap seems too specific to me though, we don't really need any of the features of snap and the cli binary doesn't have any dependencies that would need to be supplied in a snap container image. To support the largest number of platforms I think a shell command that pulls the latest version of the cli would suffice.

If we provide said shell command, would that solve your use case?

**Comment by mlec1** [comment]
I agree. I like having the latest version of my packages and be able to set up the automatic upgrade with unattended-upgrade.

As exoscale doesn't have an official apt repository, I personnally, watch the releases on Github and use this script if it can be useful (it may not be the most optimised one):

```
update-exoscale() {
    setopt localoptions rmstarsilent
    rm -rf /home/mlec/Tools/exoscale/*
    cd /home/mlec/Tools/exoscale

    echo "All previous files deleted !!"

    wget -q https://api.github.com/repos/exoscale/cli/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | grep checksums.txt | xargs wget -q && echo "Got last Exoscale CLI deb package"
    wget -q https://api.github.com/repos/exoscale/cli/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | grep linux_amd64.deb | xargs wget -q && echo "Got last Exoscale CLI checksums"

    cat exoscale-cli_*_checksums.txt | grep $(shasum -a 256 exoscale-cli_*_linux_amd64.deb | cut -f 1 -d ' ') | grep linux_amd64.deb && sudo apt install -y ./exoscale-cli_*_linux_amd64.deb && echo "New Exoscale CLI installed"

    cd -

}
```

**Comment by sauterp** [comment]
We created an install script that will install the latest version of exo cli on Red Hat- or Debian-based distros. We will need to provide it under a shorter URL of course, but for now, if you like, you may try:
```
curl -fsSL https://raw.githubusercontent.com/exoscale/cli/c6ec02e5634873f02b2542f316c9dd9ed33df1ed/install-latest.sh | sh
```
AFAICT this should also work in your GitHub Actions.

I'd value your feedback.

**Comment by mlec1** [comment]
Awesome, Thank you

**Comment by sauterp** [comment]
Installing the latest exo cli version can now be done on Red Hat- and Debian-based systems with:
```
curl -fsSL https://raw.githubusercontent.com/exoscale/cli/master/install-latest.sh | sh
```

AFAIU this solves your use cases and thus I'm closing this issue.
