### ISSUE TITLE
macOS binary has a different name

### ISSUE THREAD

**Issue by nhedger** [exoscale/cli#500]
### Description

The binary distributed for macOS is named `exoscale-cli`, while it is named `exo` in all other distributions.

I'm not sure if this is intentional, but I stumbled upon it while developing my [setup-exoscale](https://github.com/marketplace/actions/setup-exoscale) GitHub Action so I thought I'd let you know. Currently, my workaround is to create a symlink to provide the same binary name on all platforms.

**Comment by kobajagi** [comment]
Thanks @nhedger  for letting us know. I'll check if we can easily change it.
