### ISSUE TITLE
The CLI is not compatible with new role-based API keys

### ISSUE THREAD

**Issue by kosmoz** [exoscale/cli#519]
It is currently impossible to create new API keys in the web-portal and using them with the CLI. The only API keys that can be created are "new" role-based keys. The UI for creating "legacy" API keys is no longer available.

### Steps to reproduce

1. [Create a new role](https://portal.exoscale.com/u/glasskube-apps/iam/roles/add) (for testing, unrestricted access can be used, see below).
2. [Create a new API key](https://portal.exoscale.com/u/glasskube-apps/iam/keys/add) referencing that role.
3. In a terminal, run `exo config add` and supply the API key and secret key that were just generated.

### Observed behavior

The steps above result in the following output:
```
$ exo config add
[+] API Key [none]: 🫢
[+] Secret Key [none]: 🫢
Retrieving account information... failure.

Let's start over.

[+] API Endpoint [https://api.exoscale.com/v1]: 
```

I tried using different API endpoints, like `https://api.exoscale.com/v2` and `https://api-ch-gva-2.exoscale.com/v2` but those did not work either.

### Additional context

The policy I used for unrestricted access:
```json
{
  "default-service-strategy": "allow",
  "services": {}
}
```

CLI version used:
```
$ exo version
exo 1.70.0 cbb0cc49 (egoscale 0.100.1)
```

**Comment by kosmoz** [comment]
For the time being, the API key can be added to the config file manually.

This workaround was suggested by Exoscale support.

**Comment by brutasse** [comment]
Hi @kosmoz. This particular step was failing and is now fixed:

> Retrieving account information... failure.

The `exo config add` scenario works again with role-based API keys. I'll close this issue, feel free to get back if you notice anything else. Thanks!
