### ISSUE TITLE
Some questions I asked myself after first installation

### ISSUE THREAD

**Issue by mpbraendli** [exoscale/cli#529]
Hello,

In order to improve the onboarding experience, a list of things that weren't entirely clear for me.

- Do I need to create an IAM Role myself, or is there a shortcut for the cli?
- Is the "default service strategy" in the IAM role enough for the cli?
- Do I need to add "service classes" myself?

Hopefully this can help you improve the README and/or the https://community.exoscale.com/documentation/tools/exoscale-command-line-interface/ page.

**Comment by kobajagi** [comment]
Hi @mpbraendli ,

We refreshed our IAM documentation ([https://community.exoscale.com/documentation/iam/quick-start/) to include usage examples with CLI. Hopefully it will make onboarding experience smoother.

I will close this issue now, but don't hesitate to open a new one if you have further questions.
