### ISSUE TITLE
[Bug]: Snapshot default timeout

### ISSUE THREAD

**Issue by berkaykorkmaz** [exoscale/cli#543]
### Current Behavior

I have to change default timeout time, 20 minutes not enough for our instances. 
compute instance snapshot: remove hardcoded timeout and bump default timeout to 20 minutes (#493)

### CLI Version

exo 1.72.2

### Os platform

Ubuntu 22.04

### Relevant log output

```shell
error: Request timeout reached. Snapshot creation is not canceled and might still be running, check the status with: exo c i snapshot list
```

**Comment by sauterp** [comment]
Hi,
in the PR (https://github.com/exoscale/cli/pull/493) that you quoted we added the ability override the default timeout. So as far as I can see, you have all the functionality to create snapshots for large instances. Judging by the details you sent, everything works as expected and this isn't a bug. So, what's the intention of this issue? Would you like us to raise the default timeout, if so, what do you propose?

**Comment by berkaykorkmaz** [comment]
You are right, I can overwrite the timeout value. Before opening an issue, I read the release notes. After that, I tried to find this value from the exo cli help command. When I couldn't find it, I opened an issue, but unfortunately, it doesn't seem to be very helpful in the issue notes of the documentation.
Thank you.
