### ISSUE TITLE
[Feature Request]: API Keys and Role based IAM

### ISSUE THREAD

**Issue by SebiSpace** [exoscale/cli#550]
### What feature would you like to have in the cli?

Since you introduced the new role based API Keys that replace the Access Keys, it would be nice to have the changes also represented here in the cli tool.

**Comment by huerlisi** [comment]
Hi,

Is this error message related to this? It is from the tutorial to use Exoscale with Certmanager: https://www.exoscale.com/syslog/cert-manager-webhook-exoscale/.

```
exo iam access-key create \
    --operation list-dns-domains \
    --operation list-dns-domain-records \
    --operation  get-dns-domain-record \
    --operation get-operation \
    --operation create-dns-domain-record \
    --operation delete-dns-domain-record \
    cert-manager-webhook-key
error: unable to create a new IAM access key: Post "https://api-ch-dk-2.exoscale.com/v2/access-key": invalid request: Cannot generate IAMv2 `Access Key` using a IAMv3 `Api Key`
```

**Comment by sauterp** [comment]
> Hi,
> 
> Is this error message related to this? It is from the tutorial to use Exoscale with Certmanager: https://www.exoscale.com/syslog/cert-manager-webhook-exoscale/.
> 
> ```
> exo iam access-key create \
>     --operation list-dns-domains \
>     --operation list-dns-domain-records \
>     --operation  get-dns-domain-record \
>     --operation get-operation \
>     --operation create-dns-domain-record \
>     --operation delete-dns-domain-record \
>     cert-manager-webhook-key
> error: unable to create a new IAM access key: Post "https://api-ch-dk-2.exoscale.com/v2/access-key": invalid request: Cannot generate IAMv2 `Access Key` using a IAMv3 `Api Key`
> ```

Hi @huerlisi 
the error you posted is expected, IAM v2 and v3 keys can only be used to generate keys for the same major version. For a detailed reason I refer you to this answer https://github.com/exoscale/terraform-provider-exoscale/issues/290#issuecomment-1676793717

Unfortunately, implementing this feature request will not change the fact that IAM v2 and v3 keys are incompatible.

**Comment by kobajagi** [comment]
@SebiSpace New CLI release includes commands to manage Role based IAM:
https://github.com/exoscale/cli/releases/tag/v1.75.0

I'll close this ticket now don't hesitate to create a new one if you find a feature missing.
