### ISSUE TITLE
[Feature Request]:  Add SLSA provenance to your releases

### ISSUE THREAD

**Issue by udf2457** [exoscale/cli#595]
### What feature would you like to have in the cli?

Please add [SLSA provenance ](https://slsa.dev/)to your releases.

It is easy to do on on Github:

https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#provenance-for-goreleaser
https://goreleaser.com/blog/slsa-generation-for-your-artifacts/#slsa-github-generator

Background info:
https://docs.sigstore.dev/signing/overview/

Extra note:

Github announced this on 2 May which may be worth comparing to the above process incase it is easier to implement: https://github.blog/changelog/2024-05-02-artifact-attestations-public-beta/

**Comment by kobajagi** [comment]
Hi @udf2457 
Thank you for the feature request.
At the moment artifact attestation is not on our roadmap, but we are discussing it internally.
I will close this issue for now, when we are ready to commit to implement the feature I will re-open it.
