### ISSUE TITLE
[Feature Request]: Update docs to provide information for passing credentials to docker

### ISSUE THREAD

**Issue by udf2457** [exoscale/cli#624]
### What feature would you like to have in the cli?

The community docs state you can use CLI via `docker run -it exoscale/cli <command argument>`

Which is great.

But they don't say how to best pass credentials.

For example, if I have existing credentials in `$HOME/.config/exoscale/exoscale.toml` is there a way to pass them to the docker cli invocation ?  The docs are silent on this.

**Comment by pierre-emmanuelJ** [comment]
Thanks for the feedback. To use the Exoscale CLI in Docker, consider these options:

* **Environment variables:** Set `EXOSCALE_API_KEY` and `EXOSCALE_API_SECRET` before running the Docker command with `-e`.
* **Volumes:** Mount your config directory (`$HOME/.config/exoscale`) to the container using `-v`.

**Example:**

```bash
export EXOSCALE_API_KEY=your_api_key
export EXOSCALE_API_SECRET=your_api_secret
docker run -it -e EXOSCALE_API_KEY=$EXOSCALE_API_KEY -e EXOSCALE_API_SECRET=$EXOSCALE_API_SECRET exoscale/cli <command>
```

or

```bash
docker run -it -v $HOME/.config/exoscale:/root/.config/exoscale exoscale/cli <command>
```

For more details, check the Docker documentation on environment variables and volumes.
