### ISSUE TITLE
`exo eip delete` returns 0xc0...

### ISSUE THREAD

**Issue by ste-m** [exoscale/cli#99]
**To reproduce:**

    $ exo eip delete 89.145.165.61
    [+] sure you want to delete "89.145.165.61" EIP [yN]: y
    0xc00017c5e0

**Expected behaviour:**

    $ exo eip delete 89.145.165.61
    [+] sure you want to delete "89.145.165.61" EIP [yN]: y
    # either return the resource uuid as done for other cases or a human readable confirmation message

**Comment by falzm** [comment]
This problem is still present in the current version:

```console
$ exo version
exo 1.1.3 caaa0c323c51678f55c41d90f668e77f0094719b (egoscale 0.14.3)

$ exo -A ppmarc eip dissociate a.b.c.d vm0 vm1
0xc00053c3a0
0xc0006734a0
```

**Comment by pierre-emmanuelJ** [comment]
There was some change in Egoscale and then so we forget to update CLI.
thanks for report 👍 
I will implem a conformation before dissociate with redable value 😀

**Comment by falzm** [comment]
Same for `eip associate` too 😏

**Comment by pierre-emmanuelJ** [comment]
everywhere I print `ID` as a string

**Comment by falzm** [comment]
> everywhere I print `ID` as a string

![2vxz4q](https://user-images.githubusercontent.com/1122379/54293449-4a9eea00-45b0-11e9-9759-dadc4103638f.jpg)
